# static/admin/config.yml
backend:
  name: github
  repo: superemem/emen # GANTI INI: username_github/nama_repo_kamu
  branch: main
  auth_type: implicit
  app_id: Ov23liJGP9rgsb1jftEl # GANTI INI: Client ID dari aplikasi GitHub OAuth-mu
  auth_proxy_url: https://www.emen.web.id/api/auth # URL ke SvelteKit API endpoint kita

media_folder: static/uploads # Pastikan folder ini ada di root SvelteKit Anda
public_folder: /uploads

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/lib/content/blog" # Pastikan path ini benar
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Description", name: "description", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, required: true}
      - {label: "Author", name: "author", widget: "string", required: true, default: "Emen"}
      - {label: "Tags", name: "tags", widget: "list", default: ["general"], required: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}
